backend:
  name: github
  branch: main
  repo: yoeran/e-missions.nl

media_folder: "static/img"

i18n:
  structure: multiple_folders
  locales: [en, nl]
  default_locale: en

collections:
  - name: "topics"
    label: "Topics"
    label_singular: "Topic"
    folder: "src/custom-data/topics"
    create: true
    delete: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Topic title", name: "title", widget: "string", i18n: true }
      - { label: "Topic Key", name: "key", widget: "string", hint: 'This is used to find a relevant calculator' }
      - { label: "Permalink", name: "permalink", widget: "string", i18n: true }
      - { label: "Intro text", name: "body_intro_text", widget: "markdown", i18n: true }
      - label: "Tips"
        name: "tips"
        widget: "list"
        i18n: true
        fields:
          - { label: "Tip", name: "tip", widget: "string", i18n: true }
          - { label: "Explanation", name: "explanation", widget: "markdown", i18n: true }
          - { label: "Todo", name: "todo", widget: "string", required: false, i18n: true }
      - { label: "Addendum text (wow-facts)", name: "body_addendum_text", widget: "markdown", i18n: true }

  - name: "resources"
    label: "Resources"
    label_singular: "Resource"
    folder: "src/custom-data/resources"
    create: true
    delete: true
    slug: "{{year}}_{{month}}_{{day}}_{{slug}}"
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "URL", name: "url", widget: "string", required: false }
      - { label: "Description", name: "description_en", widget: "text", i18n: true }
      - label: "Category"
        name: "category"
        widget: "select"
        multiple: true
        options:
          - 'best-practice'
          - 'scientific'
          - 'smart-devices'
          - 'audio-streaming'
          - 'blockchain'
          - 'cloud-storage'
          - 'email'
          - 'online-gaming'
          - 'searching'
          - 'social-media'
          - 'video-conferencing'
          - 'video-streaming'

  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "src/pages"
    i18n: true
    delete: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Image", name: "image", widget: "image", allow_multiple: false, required: false }
      - { label: "Permalink", name: "permalink", widget: "string", i18n: true }
      - { label: "Landingpage text", name: "landingpage_text", widget: "markdown", i18n: true }
      - { label: "Intro text", name: "body_intro_text", widget: "markdown", i18n: true, required: false }
      - { label: "Main content", name: "body_main_text", widget: "markdown", i18n: true, required: false }
      - { label: "Addendum text", name: "body_addendum_text", widget: "markdown", i18n: true, required: false }
      - label: "Navigation"
        name: "eleventyNavigation"
        widget: "object"
        i18n: true
        default: { key: '', order: 0 }
        fields:
          - { label: "Key", name: "key", widget: "string", i18n: true  }
          - { label: "Order", name: "order", widget: "number", default: 0, i18n: true }

  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "src/custom-data/events"
    create: true
    delete: true
    slug: "{{year}}_{{month}}_{{day}}_{{slug}}"
    fields:
      - { label: "Organisation", name: "title", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "URL", name: "url", widget: "string", required: false, hint: 'Always include the https://' }

  - name: "members"
    label: "Members"
    label_singular: "Member"
    folder: "src/custom-data/members"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Project Role", name: "role", widget: "string" }
      - { label: "Image", name: "image", widget: "image", allow_multiple: false, required: false }
      - { label: "LinkedIn", name: "linkedin", widget: "string", required: false, hint: 'Always include the https://' }
      - { label: "Website", name: "website", widget: "string", required: false, hint: 'Always include the https://' }
      - { label: "Text about project", name: "content", required: false, widget: "markdown" }

  - name: "snippets"
    label: "Text Snippets"
    label_singular: "Text Snippet"
    folder: "src/custom-data/text-snippets"
    create: true
    delete: false
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", hidden: true }
      - { label: "Homepage: Title", name: "homepage_intro_title", widget: "string", i18n: true }
      - { label: "Homepage: Intro", name: "homepage_intro_text", widget: "text", i18n: true }
      - { label: "Homepage: Calculator title", name: "homepage_calculator_title", widget: "string", i18n: true }
      - { label: "Homepage: Calculator description", name: "homepage_calculator_text", widget: "markdown", i18n: true }
      - { label: "Homepage: Take Action title", name: "homepage_take_action_title", widget: "string", i18n: true }
      - { label: "Homepage: Take Action description", name: "homepage_take_action_text", widget: "markdown", i18n: true }
      - { label: "Homepage: Take Action button", name: "homepage_take_action_button", widget: "string", i18n: true }
      - { label: "Homepage: Topic title", name: "homepage_topic_title", widget: "string", i18n: true }
      - { label: "Homepage: Topic text", name: "homepage_topic_text", widget: "markdown", i18n: true }
      - { label: "Resources: Intro title", name: "resources_intro_title", widget: "string", i18n: true }
      - { label: "Resources: Intro text", name: "resources_intro_text", widget: "markdown", i18n: true }
      - { label: "Tips text", name: "tips_text", widget: "markdown", i18n: true }
      - { label: "Footer: About text", name: "footer_about", widget: "markdown", i18n: true }
