backend:
  name: github
  branch: main
  repo: yoeran/e-missions.nl

media_folder: "static/img"

i18n:
  structure: multiple_folders
  locales: [en, nl]
  default_locale: en

collections:
  # Our blog posts
  - name: "resources" # Used in routes, e.g., /admin/collections/blog
    label: "Resources" # Used in the UI
    folder: "src/resources" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    structure: single_file
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "URL", name: "url", widget: "string", required: false }
      - { label: "Description", name: "description_en", widget: "text", i18n: true }
      - { label: "Category", name: "category", widget: "select", multiple: true, options: ['calculator','art','best-practice','scientific'] }

  # Our pages e.g. About
  - name: "pages"
    label: "Pages"
    folder: "src"
    i18n: true
    create: true # Change to true to allow editors to create new pages
    delete: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Image", name: "image", widget: "string", allow_multiple: false }
      - { label: "Permalink", name: "permalink", widget: "string", i18n: true }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string", i18n: true }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Intro", name: "body_intro", widget: "markdown", i18n: true }
      - { label: "Main content", name: "body_main", widget: "markdown", i18n: true }
      - { label: "Addendum", name: "body_addendum", widget: "markdown", i18n: true }

  # - name: "pages-nl"
  #   label: "Page (NL)"
  #   folder: "src/nl/pages"
  #   create: false # Change to true to allow editors to create new pages
  #   delete: false
  #   slug: "{{slug}}"
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Permalink", name: "permalink", widget: "string" }
  #     - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
  #       name: "eleventyNavigation"
  #       widget: "object"
  #       fields:
  #         - { label: "Key", name: "key", widget: "string" }
  #         - { label: "Order", name: "order", widget: "number", default: 0 }
  #     - { label: "Body", name: "body", widget: "markdown" }