backend:
  name: github
  branch: main
  repo: yoeran/e-missions.nl

media_folder: "static/img"
publish_mode: editorial_workflow

collections:
  # Our blog posts
  - name: "resources" # Used in routes, e.g., /admin/collections/blog
    label: "Resource" # Used in the UI
    folder: "resources" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "URL", name: "url", widget: "string", required: false }
      - { label: "Description (EN)", name: "description_en", widget: "text" }
      - { label: "Description (NL)", name: "description_nl", widget: "text" }
      - { label: "Category", name: "category", widget: "select", multiple: true, options: ['calculator','art','best-practice','scientific'] }

  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: false # Change to true to allow editors to create new pages
    delete: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Body", name: "body", widget: "markdown" }